markdown: kramdown
baseurl: "https://www.laposolutions.com"
exclude: ['README.md']
defaults:
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"

 
